[package]
name = "simulation_async"
version = "0.1.0"
authors = ["Umur Gedik <umurgdk@gmail.com>"]

[dependencies]
soundlines_core = { path = "../soundlines_core" }
log = "0.3"
env_logger = "0.4"
time = "0.1"
error-chain = "0.11"
redis = "0.8"
serde = "1.0"
serde_derive = "1.0"
serde_json = "1.0"