/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class SoundlinesCore */

#ifndef _Included_SoundlinesCore
#define _Included_SoundlinesCore
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     SoundlinesCore
 * Method:    init
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_SoundlinesCore_init
  (JNIEnv *, jclass);

/*
 * Class:     SoundlinesCore
 * Method:    getEntities
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_SoundlinesCore_getEntities
  (JNIEnv *, jclass);

#ifdef __cplusplus
}
#endif
#endif
