[package]
name = "rocket_jwt"
version = "0.1.0"
authors = ["Umur Gedik <umurgdk@gmail.com>"]

[dependencies]
rocket = "0.3"
jsonwebtoken = "2"
serde = "*"

[dev-dependencies]
rocket_codegen = "0.3"
serde_derive = "*"
